serverAddr = "110.42.96.64"
serverPort = 8500
metadatas.id = "R2tAJY24xq"
transport.heartbeatInterval = 120

[[proxies]]
name = "51078dc4-a861-4af8-83f3-17770c71cf70"
type = "tcp"
localIP = "127.0.0.1"
localPort = 22

[[proxies]]
name = "e0fcd285-4478-466f-938b-cd7833f994dd"
type = "tcp"
localIP = "127.0.0.1"
localPort = 22

[[proxies]]
name = "f78adb14-4656-4c2d-8e56-52341bdccecf"
type = "tcp"
localIP = "127.0.0.1"
localPort = 22